      PARAMETER (ISC=1)




      PARAMETER ( NTRUN=63, MTRUN=63, IX=192, IY=48 )   



      PARAMETER (NX=NTRUN+2, MX=MTRUN+1 , MXNX=MX*NX,MX2=2*MX)
      PARAMETER (IL=2*IY, NTRUN1=NTRUN+1 )
      PARAMETER (NXP=NX+1 , MXP=ISC*MTRUN+1, LMAX=MXP+NX-2 )
